//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int Id { get; set; }
        public Nullable<int> IdFood1 { get; set; }
        public Nullable<int> IdFood2 { get; set; }
        public Nullable<int> IdFood3 { get; set; }
        public string HashVenta { get; set; }
        public bool Received { get; set; }
        public bool Start { get; set; }
        public int TimeWait { get; set; }
        public int IdRestaurant { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
